---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(rnoaa)
library(lubridate)
library(flexdashboard)

# Fetch weather data from rnoaa
weather_df <- rnoaa::meteo_pull_monitors(
  c("USW00094728", "USW00022534", "USS0023B17S"),
  var = c("PRCP", "TMIN", "TMAX"),
  date_min = "2021-01-01",
  date_max = "2022-12-31"
) |>
  mutate(
    name = recode(
      id,
      "USW00094728" = "CentralPark_NY",
      "USW00022534" = "Molokai_HI",
      "USS0023B17S" = "Waterhole_WA"
    ),
    tmin = tmin / 10,
    tmax = tmax / 10,
    prcp = prcp / 10
  )

```
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# Scatter Plot
scatter_plot <- plot_ly(weather_df, x = ~tmin, y = ~tmax, color = ~name, type = 'scatter', mode = 'markers') |>
  layout(
    title = "Scatter Plot of Maximum vs. Minimum Daily Temperatures",
    xaxis = list(title = "Minimum Temperature (°C)"),
    yaxis = list(title = "Maximum Temperature (°C)")
  )
scatter_plot
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
# Line Plot
line_plot <- plot_ly(weather_df, x = ~date, y = ~tmax, color = ~name, type = 'scatter', mode = 'lines') |>
  layout(
    title = "Daily Maximum Temperature Over Time",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Maximum Temperature (°C)")
  )
line_plot
```

### Chart C

```{r}
weather_df |>
  select(name, tmax, tmin) |> 
  pivot_longer(
    tmax:tmin,
    names_to = "observation", 
    values_to = "temp") |> 
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5) + 
  facet_grid(~name) +
  ggtitle("Precipitation Density by Location") +
  labs(
    x = "Temperature (°C)",
    y = "Density",
    fill = "Observation"
  )
```